accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path(
        'reset/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'),
        name='password_reset'),
    path(
        'reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('create/', include('slide_create.urls')),
    path('admin/', admin.site.urls),
    path('prog/',include('prog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

prog/urls.py
from django.urls import path
from . import views

app_name='prog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:language>/',views.index,name='index'),
    path('<str:language>/<int:pk>/',views.learn,name='learn'),
    path('setting/user/',views.setting,name='setting'),
    path('edit/',views.edit,name='edit'),
]

slide_create/urls.py
from django.urls import path
from . import views 

app_name = 'slide_create'

urlpatterns = [
    path('',views.list,name='list'),
    path('create_lang/',views.create_lang,name='create_lang'),
    path('<int:pk>/',views.lang,name='lang'),
    path('<int:pk>/new/', views.new_slide, name='new_slide'),
]

accounts/models.py
from django.db import models

# Create your models here.

prog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ProgramingLanguage(models.Model):
    language = models.CharField(max_length=20)
    offical_text = models.TextField(max_length=1000)
    def __str__(self):
        return self.language

class Slide(models.Model):
    plograming_language = models.ForeignKey(ProgramingLanguage,on_delete=models.CASCADE,related_name='slide')
    slide_url = models.URLField(max_length=200)
    title = models.CharField(max_length=50)
    explain = models.TextField(max_length=1000)
    max_rep_num = models.IntegerField(default=1)
    def __str__(self):
        return self.title

class Post(models.Model):
    message = models.TextField(max_length=4000)
    slide = models.ForeignKey(Slide,on_delete=models.CASCADE,related_name='post')
    post_at = models.DateTimeField(null=True)
    post_by = models.ForeignKey(User,on_delete=models.CASCADE,related_name='post')
    rep_num = models.IntegerField(default=0)
    def __str__(self):
        return self.message

slide_create/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

slide_create/forms.py
from django import forms
from prog.models import Slide,ProgramingLanguage

class NewSlideForm(forms.ModelForm):
    class Meta:
        model = Slide
        fields = ['title', 'slide_url', 'explain']

class NewLangForm(forms.ModelForm):
    class Meta:
        model = ProgramingLanguage
        fields = ['language', 'offical_text']

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect

from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('prog:home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

prog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from .models import ProgramingLanguage,Slide
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
import json

@login_required
def home(request):
    lang = ProgramingLanguage.objects.all()
    return render(request, 'prog/home.html', {'lang':lang})

@login_required
def index(request,language):
    lang = ProgramingLanguage.objects.all()
    language = get_object_or_404(ProgramingLanguage,language=language)
    return render(request, 'prog/index.html', {'lang':lang,'language':language})

@login_required
def learn(request,language,pk):
    lang = ProgramingLanguage.objects.all()
    slide = get_object_or_404(Slide,pk=pk)
    room_name = language + str(pk)
    content = {
        'room_name_json': mark_safe(json.dumps(room_name)),
        'lang':lang,
        'slide':slide
        }
    return render(request, 'prog/learn.html', content)

def edit(request):
    user = User.objects.first()
    lang = ProgramingLanguage.objects.all()
    content = {
        'lang':lang,
        'slide':slide,
        'user':user,
        }
    return render(request, 'prog/edit.html', content)

@login_required
def setting(request):
    lang = ProgramingLanguage.objects.all()
    return render(request, 'prog/setting.html', {'lang':lang})


slide_create/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from prog.models import ProgramingLanguage,Slide
from django.contrib.auth.models import User
from .forms import NewSlideForm,NewLangForm

def list(request):
    prog = ProgramingLanguage.objects.all()
    return render(request,'slide_create/list.html',{'prog':prog})

def create_lang(request):
    if request.method == 'POST':
        form = NewLangForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('slide_create:list')
    else:
        form = NewLangForm()
    return render(request,'slide_create/create_lang.html',{'form':form})
    

def lang(request,pk):
    lang = get_object_or_404(ProgramingLanguage,pk=pk)
    return render(request,'slide_create/lang.html',{'lang':lang})

def new_slide(request,pk):
    lang = get_object_or_404(ProgramingLanguage,pk=pk)

    if request.method == 'POST':
        form = NewSlideForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.plograming_language = lang
            form.save()
            return redirect('slide_create:lang',pk=lang.pk)
    else:
        form = NewSlideForm()
    return render(request,'slide_create/new_slide.html',{'lang':lang,'form':form})

accounts/templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Prog Team

prog/templates/prog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'prog/prog.css' %}">
    <title>{% block title %}Prog{% endblock %}</title>
</head>

<body>
    <div class="head_test-wrap">
        <h1 class="head_test"><a class="prog" href="{% url 'prog:home' %}">
                Prog
            </a></h1>
    </div>
    <script type="text/javascript">
        function jump() {
            location.href = "{% url 'prog:edit' %}";
        }
    </script>
    <!--ここからメニュー-->
    <ul id="nav-menu">
        <li><a href="{% url 'prog:home' %}">HOME</a></li>
        <li class="hover-click"><a><i class="blogicon-reorder"></i>Index</a>
            <ul>
                {% for l in lang %}
                <li><a href="{% url 'prog:index' l.language %}">{{ l.language }}</a></li>
                {% endfor %}
            </ul>
        </li>
        <li class="hover-click"><a href="#"><i class="blogicon-reorder"></i>Other</a>
            <ul>
                <li><a href="{% url 'prog:setting' %}">Setting</a></li>
                <li><a href="{% url 'logout' %}">logout</a></li>
            </ul>
        </li>
    </ul>

    <!--jQueryを使用-->
    <script src="https://code.jquery.com/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            var contents = $(".hover-click > ul");
            $(".hover-click > a").click(function () {
                $(contents).toggle();
                return false;
            });
            $(".hover-click")
                .mouseover(function () {
                    $(contents).show();
                })
                .mouseout(function () {
                    $(contents).hide();
                });
        });
    </script>
    <!--ここまでメニュー-->
    <br />
    <div class="head_test-wrap2">
        <h1 class="head_test2">
            {% block head %}
            {% endblock %}
        </h1>
    </div>
    {% block content %}
    {% endblock %}
    <div class="btm">
        <div class="copyright">
            <br />
            <p>Copyright(C) 2018-2019 <a href="https://www.iniad.org/">INIAD</a> All Rights Reserved</p>
            <br />
        </div>
    </div>

</body>
{% block endbody %}
{% endblock %}

</html>

prog/templates/prog/edit.html
{% extends 'prog/base.html' %}

{% block title %}edit{% endblock %}

{% block head %}Edit{% endblock %}

{% block content %}
<br />

<div id="slide_1">
    <iframe id="slide"></iframe>
    <script>
        var slide = document.getElementById('slide');
        //slide.src = "https://docs.google.com/presentation/d/1k9Yfibe3QxeVMMHkr0GDkkcRJXThbiqvETYUu_KtKBI/embed?start=false&amp;loop=false&amp;delayms=3000&slide=id.g4947a87a01_0_76";
        slide.src = "https://docs.google.com/presentation/d/1a0kaf62tE4BK49Esnz-JC05156G51S-wyixD-glF7lU/edit#slide=id.g31045d592f_1_0";
        slide.allowfullscreen = true;
        slide.frameborder = 0;
        slide.mozallowfullscreen = true;
        slide.webkitallowfullscreen = true;
        slide.height = 479;
        slide.width = 800;
    </script>
</div>

<div id="chat">
    <textarea id="chat-log" cols="100" rows="20"></textarea><br />
    <input id="chat-message-input" type="text" size="100" /><br />
    <input id="chat-message-submit" type="button" value="Send" />
</div>

<script>
    var chatSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/prog/edit/');
    chatSocket.onmessage = function (e) {
        var data = JSON.parse(e.data); var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };
    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };
    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };
    document.querySelector('#chat-message-submit').onclick = function (e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({ 'message': message }));
        messageInputDom.value = '';
    };
</script>

</script>
</div>
{% endblock %}

prog/templates/prog/home.html
{% extends 'prog/base.html' %}

{% block title %}home{% endblock %}

{% block head %}Home{% endblock %}

{% block content %}
<br />
<div class="frame">
  {% for l in lang %}

  <div class="index">
    <a href="{% url 'prog:index' l.language %}">
    <button class="btn" type="button" onclick="jump()">{{ l.language }}</button>
    </a>
    <h2>
      {{ l.offical_text }}</h2>
  </div>
  {% endfor %}
</div>

{% endblock %}

prog/templates/prog/index.html
{% extends 'prog/base.html' %}

{% block title %}index{% endblock %}

{% block head %}{{ language.language }}{% endblock %}

{% block content %}

<div class="contents">
    {% for slide in language.slide.all %}

    <div class="cont">
        <h2>{{ slide.title }}</h2>
        <a href="{% url 'prog:learn' language.language slide.pk %}">
        <li style="list-style-type: none">{{ slide.explain }}<button type="button" class="button">Go!</button></a></li>
    </div>
    {% endfor %}
</div>

{% endblock %}

prog/templates/prog/learn.html
{% extends 'prog/base.html' %}

{% block title %}{{ slide.title }}{% endblock %}

{% block head %}{{ slide.title }}{% endblock %}

{% block content %}
<br />

<div id="slide_1">
    <iframe id="slide"></iframe>
    <script>
        var slide = document.getElementById('slide');
        //slide.src = "https://docs.google.com/presentation/d/1k9Yfibe3QxeVMMHkr0GDkkcRJXThbiqvETYUu_KtKBI/embed?start=false&amp;loop=false&amp;delayms=3000&slide=id.g4947a87a01_0_76";
        slide.src = "{{ slide.slide_url}}";
        slide.allowfullscreen = true;
        slide.frameborder = 0;
        slide.mozallowfullscreen = true;
        slide.webkitallowfullscreen = true;
        slide.height = 479;
        slide.width = 800;

    </script>
</div>

<br />

<div class="head_test-wrap2">
    <h1 class="head_test2">
        chat
    </h1>
</div>

<div class="chat">
    <div id='chat2'>
    {% for post in slide.post.all %}
    <p style="background-color:rgb(233, 233, 233);">{{ post.rep_num }} {{ post.post_by.username }} : {{ post.post_at }}</p>
    <p style="background-color: rgb(255, 255, 255)">{{ post.message }}</p>
    {% endfor %}

    <p id='name' style='background-color:rgb(233, 233, 233);'></p>

    </div>

    </br>

    <textarea id="chat-message-input" cols="40" rows="7"></textarea><br />
    <input id="chat-message-submit" type="button" value="Send" />

</div>

    {% endblock %}

{% block endbody %}
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/prog/' + roomName + '/');

    chatSocket.onmessage = function (e) {
        var id = document.getElementById('chat2')
        var data = JSON.parse(e.data);
        var message = "<p style='background-color: rgb(255, 255, 255)'>" + data['message'] + '</p>';
        var num = data['rep'];
        var name = data['user'];
        var time = data['time'];
        name_text = "<p style='background-color:rgb(233, 233, 233);'>" + num + ' ' + name + ' : ' + time + '</p>'
        id.insertAdjacentHTML('beforeend',name_text);
        id.insertAdjacentHTML('beforeend',message);
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) { // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        var pk = {{ slide.pk }};
    chatSocket.send(JSON.stringify({
        'message': message,
        'pk': pk
    }));
    messageInputDom.value = '';
    //location.reload();
    };
</script>
{% endblock %}

prog/templates/prog/setting.html
{% extends 'prog/base.html' %}

{% block title %}setting{% endblock %}

{% block head %}Setting{% endblock %}

{% block content %}
<div class="set">
    <h1>user information</h1>
    <li>Your name: {{ user.username }}</li>
    <li>Your Email address: {{ user.email }}</li>
    <br />
</div>
<div>
    <button type="button" class="set_button">Chenge my information!</button>
</div>
{% endblock %}

slide_create/templates/base2.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
      {% block body %}
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
    {% endblock %}
  </body>
</html>

slide_create/templates/includes/form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text }}
      </small>
    {% endif %}
  </div>
{% endfor %}

slide_create/templates/slide_create/create_lang.html
{% extends 'base2.html' %}

{% block title %}Start a New Slide{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'slide_create:list' %}">list</a></li>
<li class="breadcrumb-item active">New language</li>
{% endblock %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

slide_create/templates/slide_create/lang.html
{% extends 'base2.html' %}

{% block title %}lang{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'slide_create:list' %}">list</a></li>
<li class="breadcrumb-item"><a href="{% url 'slide_create:lang' lang.pk %}">{{ lang.language }}</a></li>
{% endblock %}

{% block content %}

<div class="mb-4">
    <a href="{% url 'slide_create:new_slide' lang.pk %}" class="btn btn-primary">New topic</a>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>title</th>
            <th>explain</th>
        </tr>
    </thead>
    <tbody>
        {% for slide in lang.slide.all %}
        <tr>
            <td>{{ slide.title }}</td>
            <td>{{ slide.explain }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

slide_create/templates/slide_create/list.html
{% extends 'base2.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item active">list</li>
{% endblock %}

{% block content %}

<div class="mb-4">
    <a href="{% url 'slide_create:create_lang' %}" class="btn btn-primary">New lang</a>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>language</th>
        </tr>
    </thead>
    <tbody>
        {% for p in prog %}
        <tr>
            <td>
                <a href="{% url 'slide_create:lang' p.pk %}">
                    {{ p.language }}
                </a>
                <small class="text-muted d-block">{{ p.offical_text }}</small>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

slide_create/templates/slide_create/new_slide.html
{% extends 'base2.html' %}

{% block title %}Start a New Slide{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'slide_create:list' %}">list</a></li>
<li class="breadcrumb-item"><a href="{% url 'slide_create:lang' lang.pk %}">{{ lang.language }}</a></li>
<li class="breadcrumb-item active">New slide</li>
{% endblock %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}